management:
  security:
    enabled: false
  context-path: /admin
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    url: jdbc:postgresql://db/postgres
    username: postgres
    password: example
    driver-class-name: org.postgresql.Driver
  data:
    rest:
      base-path: /api
#      defaultMediaType: application/json
logging:
  file: /logs/file-storage.log