spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: H2
    properties:
      javax.persistence.schema-generation.create-source: metadata
      javax.persistence.schema-generation.scripts.action: create
      javax.persistence.schema-generation.scripts.create-target: /tmp/file-storage/db/schema.sql
  datasource:
    url: jdbc:h2:mem:dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
#    url: jdbc:h2:/tmp/file-storage/db/dev;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialize: true
    data: classpath:data-dev.sql
logging:
  file: /tmp/file-storage/application.log