-- DROP TABLE content;
-- CREATE TABLE content (
--   id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
--   content_data_id    BIGINT,
--   create_date        TIMESTAMP,
--   last_modified_date TIMESTAMP,
--   name               VARCHAR(255)   NOT NULL,
--   size               INT DEFAULT -1 NOT NULL,
--   type               VARCHAR(255)   NOT NULL,
--   version            BIGINT,
--   PRIMARY KEY (id)
-- );
INSERT INTO content (id, name, type, size, content_data_id, create_date, last_modified_date, version)
VALUES (1, 'file.xml', 'application/xml', 0, 1, '2000-01-01', '2000-01-01', 0);
INSERT INTO content (id, name, type, size, content_data_id, create_date, last_modified_date, version)
VALUES (2, 'file.xml', 'application/xml', 0, 2, '2000-01-01', '2000-01-01', 0);
-- SELECT * FROM content;